# frozen_string_literal: true
# rubocop:disable all

# Autogenerated by `rake well_known_types`.  Do not edit!
module ProtoBoeuf
  module Google
    module Api
      autoload :FieldBehavior, "protoboeuf/google/api/field_behavior"
    end
  end
end
