# frozen_string_literal: true
# rubocop:disable all

# Autogenerated by `rake well_known_types`.  Do not edit!
module ProtoBoeuf
  module Google
    module Protobuf
      autoload :Any, "protoboeuf/google/protobuf/any"
      autoload :BoolValue, "protoboeuf/google/protobuf/boolvalue"
      autoload :BytesValue, "protoboeuf/google/protobuf/bytesvalue"
      autoload :DescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :DoubleValue, "protoboeuf/google/protobuf/doublevalue"
      autoload :Duration, "protoboeuf/google/protobuf/duration"
      autoload :Edition, "protoboeuf/google/protobuf/descriptor"
      autoload :EnumDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :EnumOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :EnumValueDescriptorProto,
               "protoboeuf/google/protobuf/descriptor"
      autoload :EnumValueOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :ExtensionRangeOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :FeatureSet, "protoboeuf/google/protobuf/descriptor"
      autoload :FeatureSetDefaults, "protoboeuf/google/protobuf/descriptor"
      autoload :FieldDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :FieldMask, "protoboeuf/google/protobuf/field_mask"
      autoload :FieldOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :FileDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :FileDescriptorSet, "protoboeuf/google/protobuf/descriptor"
      autoload :FileOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :FloatValue, "protoboeuf/google/protobuf/floatvalue"
      autoload :GeneratedCodeInfo, "protoboeuf/google/protobuf/descriptor"
      autoload :Int32Value, "protoboeuf/google/protobuf/int32value"
      autoload :Int64Value, "protoboeuf/google/protobuf/int64value"
      autoload :ListValue, "protoboeuf/google/protobuf/struct"
      autoload :MessageOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :MethodDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :MethodOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :NullValue, "protoboeuf/google/protobuf/struct"
      autoload :OneofDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :OneofOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :ServiceDescriptorProto, "protoboeuf/google/protobuf/descriptor"
      autoload :ServiceOptions, "protoboeuf/google/protobuf/descriptor"
      autoload :SourceCodeInfo, "protoboeuf/google/protobuf/descriptor"
      autoload :StringValue, "protoboeuf/google/protobuf/stringvalue"
      autoload :Struct, "protoboeuf/google/protobuf/struct"
      autoload :Timestamp, "protoboeuf/google/protobuf/timestamp"
      autoload :UInt32Value, "protoboeuf/google/protobuf/uint32value"
      autoload :UInt64Value, "protoboeuf/google/protobuf/uint64value"
      autoload :UninterpretedOption, "protoboeuf/google/protobuf/descriptor"
      autoload :Value, "protoboeuf/google/protobuf/struct"
    end
  end
end
