# frozen_string_literal: true
# rubocop:disable all

# Autogenerated by `rake well_known_types`.  Do not edit!
module ProtoBoeuf
  module Google
    module TestProtos
      autoload :Bicycle,
               "../test/fixtures/autoloadergen/google/test_protos/transportation"
      autoload :Boat,
               "../test/fixtures/autoloadergen/google/test_protos/transportation"
      autoload :Color, "../test/fixtures/autoloadergen/google/test_protos/color"
      autoload :Vehicle,
               "../test/fixtures/autoloadergen/google/test_protos/transportation"
    end
  end
end
