#!/usr/bin/env ruby
# frozen_string_literal: true

require "protoboeuf/codegen"
require "optparse"

generate_types = false

op = OptionParser.new do |opts|
  opts.banner = "Usage: protoboeuf file.bproto"
  opts.on("-t", "--typed", "Generate sorbet types") { generate_types = true }
end
op.parse!

def parse_binary(file)
  require "protoboeuf/google/protobuf/descriptor"
  ProtoBoeuf::Google::Protobuf::FileDescriptorSet.decode(File.binread(file))
end

if ARGV[0] && File.exist?(ARGV[0])
  unit = parse_binary(ARGV[0])

  gen = ProtoBoeuf::CodeGen.new(unit, generate_types:)
  puts gen.to_ruby
else
  $stderr.puts op
  exit 1
end
