#!/usr/bin/env ruby
# frozen_string_literal: true

require "protoboeuf/codegen"
require "protoboeuf/parser"
require "optparse"

generate_types = false
binary = false

op = OptionParser.new do |opts|
  opts.banner = "Usage: protoboeuf file.proto"
  opts.on("-t", "--typed", "Generate sorbet types") { generate_types = true }
  opts.on("-b", "--bin", "Read binary proto file") { binary = true }
end
op.parse!

if ARGV[0] && File.exist?(ARGV[0])
  unit = if binary
    require "google/protobuf/descriptor_pb"
    Google::Protobuf::FileDescriptorSet.decode File.binread ARGV[0]
  else
    ProtoBoeuf.parse_file(ARGV[0])
  end

  gen = ProtoBoeuf::CodeGen.new(unit, generate_types:)
  puts gen.to_ruby
else
  $stderr.puts op
  exit 1
end
