#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "protoboeuf/codegen"
require "protoboeuf/parser"
require "optparse"

op = OptionParser.new do |opts|
  opts.banner = "Usage: protoboeuf file.proto"
end
op.parse!

if ARGV[0] && File.exist?(ARGV[0])
  unit = ProtoBoeuf.parse_file(ARGV[0])
  gen = ProtoBoeuf::CodeGen.new(unit)
  puts gen.to_ruby
else
  $stderr.puts op
  exit 1
end
