name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: shopify-${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: [ head, 3.2 ]

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
